// Generated by scripts/tts_build.py. Frames start at 1 and are inclusive.
export const TOTAL_FRAMES = 991;
export const CHAPTER_STARTS: Array<{n: number; title: string; from: number}> = [
  {n: 1, title: "The problem", from: 86},
  {n: 2, title: "The pipeline", from: 507},
];
export type Sentence = {id: string; chapter: number; from: number; to: number; text: string};
export const SENTENCES: Sentence[] = [
  {id: "S01", chapter: 1, from: 86, to: 207, text: "A language model answers from memory. Its knowledge has a cutoff."},
  {id: "S02", chapter: 1, from: 218, to: 321, text: "Ask about last week, and it may invent an answer."},
  {id: "S03", chapter: 1, from: 332, to: 451, text: "Retrieval-augmented generation gives the model an open book."},
  {id: "S04", chapter: 2, from: 507, to: 637, text: "Index. Documents are split into chunks and stored as vectors."},
  {id: "S05", chapter: 2, from: 648, to: 740, text: "Retrieve. The question finds the closest chunks."},
  {id: "S06", chapter: 2, from: 751, to: 890, text: "Generate. The answer is written from those passages, with citations."},
];
