// Generated by scripts/tts_build.py (per-block synthesis -> subtitle blocks). Placeholder until the
// voiceover runs. To edit subtitles, edit script/narration.txt and rerun the script.
export type SubEntry = {from: number; to: number; text: string};
export const SUBS: SubEntry[] = [];
