// Generated by scripts/tts_build.py (placeholder until the voiceover runs). Frames start at 1 and are inclusive.
export const TOTAL_FRAMES = 300;
export const CHAPTER_STARTS: Array<{n: number; title: string; from: number}> = [];
export type Sentence = {id: string; chapter: number; from: number; to: number; text: string};
export const SENTENCES: Sentence[] = [];
