/**
 * Film-level config (one of the two per-topic files; the other is script/narration.txt).
 * Sentence ids (S01...) come from src/common/timeline.ts, generated by scripts/tts_build.py;
 * chapter count and titles come from the `# CHAPTER n title` lines in narration.txt.
 */
export type HudEntry = {fromS: string; toS: string; text: string; tech?: string; fromOffset?: number; toOffset?: number; w?: number};
export type RailSpec = {steps: string[]; switchS: string[]; fromS: string; toS: string};
export const VIDEO = {
  slug: 'rag-poster', // asset dir public/assets/<slug>/ (audio.wav is written there by tts_build.py)
  /** Style pack: 'paper' (default) | 'instrument' | 'poster'. One pack per film. */
  style: 'poster' as 'paper' | 'instrument' | 'poster',
  /** Film language. English only: the scripts abort on any CJK character. */
  lang: 'en' as 'en',
  /** Legacy backdrop of the classic pack ('stars' | 'dots'); retires with that pack. */
  bg: 'stars' as 'stars' | 'dots',
  /** Subtitles on/off. Off only hides the band; the layout and timings do not change. */
  subtitles: true,
  title: {big: 'Retrieval', rest: 'augmented generation', en: 'Retrieval-Augmented Generation', tagline: 'How language models pass open-book exams'},
  credit: {kicker: 'BASED ON', title: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks', byline: 'Lewis et al. · NeurIPS 2020', note: 'all visuals drawn in code'} as {kicker: string; title: string; byline: string; note: string} | null,
  chapterTech: ['Why RAG', 'Retrieval & Generation'],
  hud: [
    {fromS: 'S01', toS: 'S03', text: 'The problem'},
    {fromS: 'S04', toS: 'S06', text: 'The pipeline'},
  ] as HudEntry[],
  rails: [] as RailSpec[],
  endingFade: 30,
};
