/**
 * Film-level config (one of the two per-topic files; the other is script/narration.txt).
 * Sentence ids (S01...) come from src/common/timeline.ts, generated by scripts/tts_build.py;
 * chapter count and titles come from the `# CHAPTER n title` lines in narration.txt.
 */
export type HudEntry = {fromS: string; toS: string; text: string; tech?: string; fromOffset?: number; toOffset?: number; w?: number};
export type RailSpec = {steps: string[]; switchS: string[]; fromS: string; toS: string};
export const VIDEO = {
  slug: 'demo', // asset dir public/assets/<slug>/ (audio.wav is written there by tts_build.py)
  /**
   * Style pack: 'paper' (default) | 'instrument' | 'poster'. One pack per film.
   * Packs live in src/styles/<pack>/ and are re-exported by src/ui.tsx.
   */
  style: 'paper' as 'paper' | 'instrument' | 'poster',
  /**
   * Film language. English only: the scripts abort on any CJK character.
   * Affects title squeeze (Latin is never squeezed) and centred-text baseline compensation.
   */
  lang: 'en' as 'en',
  /** Legacy backdrop of the classic pack ('stars' | 'dots'); retires with that pack. */
  bg: 'stars' as 'stars' | 'dots',
  /** Subtitles on/off. Off only hides the band; the layout and timings do not change. */
  subtitles: true,
  /**
   * Title card. big: display word (Paper accents it); rest: optional second line; en: full name or
   * subtitle; tagline: one-line hook.
   */
  title: {big: 'RAG', rest: '', en: 'Retrieval-Augmented Generation', tagline: 'How LLMs pass open-book exams'},
  /** Closing credit card (content dims + ~2 s after the last sentence; null hides it) */
  credit: {kicker: 'BASED ON', title: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks', byline: 'Lewis et al. · NeurIPS 2020', note: 'all visuals drawn in code'} as {kicker: string; title: string; byline: string; note: string} | null,
  /** Chapter subtitles, in narration CHAPTER 1..n order (chapter cards start from chapter 2) */
  chapterTech: ['Why RAG', 'Indexing', 'Retrieval & Generation', 'Evaluation & Advanced RAG'],
  /** Top HUD capsule (current section name): sentence-id ranges, no gaps between neighbours */
  hud: [
    {fromS: 'S01', toS: 'S05', text: 'The LLM gap'},
    {fromS: 'S06', toS: 'S07', text: 'Open-book exams'},
    {fromS: 'S08', toS: 'S10', text: 'RAG', tech: 'Retrieval-Augmented Generation'},
  ] as HudEntry[],
  /** Pipeline rail (optional, one per chapter, up to five steps): y118-162; rail chapters use y175-620 for content */
  rails: [
    {steps: ['Parse', 'Chunk', 'Embed', 'Index', 'Update'], switchS: ['S12', 'S13', 'S16', 'S18', 'S20'], fromS: 'S12', toS: 'S20'},
  ] as RailSpec[],
  /** Intro length in frames (LEAD+CHAPTER_GAP from tts_build, usually 85) and the closing fade */
  endingFade: 30,
};
