// Generated by scripts/tts_build.py (per-block synthesis -> subtitle blocks).
// To edit subtitles, edit script/narration.txt and rerun.
export type SubEntry = {from: number; to: number; text: string};
export const SUBS: SubEntry[] = [
  {from: 86, to: 156, text: "A language model answers from memory."},
  {from: 157, to: 207, text: "Its knowledge has a cutoff."},
  {from: 218, to: 266, text: "Ask about last week,"},
  {from: 267, to: 321, text: "and it may invent an answer."},
  {from: 332, to: 393, text: "Retrieval-augmented generation"},
  {from: 394, to: 451, text: "gives the model an open book."},
  {from: 507, to: 533, text: "Index."},
  {from: 534, to: 589, text: "Documents are split into chunks"},
  {from: 590, to: 637, text: "and stored as vectors."},
  {from: 648, to: 677, text: "Retrieve."},
  {from: 678, to: 740, text: "The question finds the closest chunks."},
  {from: 751, to: 778, text: "Generate."},
  {from: 779, to: 850, text: "The answer is written from those passages,"},
  {from: 851, to: 890, text: "with citations."},
];
